### ISSUE TITLE
Uncaught ReferenceError in Edition theme

### ISSUE THREAD

**Issue by greenhamsam** [gmfmi/searchinghost-easy#7]
Hiya! Thanks for the brilliant work on this - it's exactly the search solution I was looking for.

I'm having an issue getting the search icon to display. Triggering search from the word "Search" works fine.

**Configuration**
- My website is [https://sambeckbessinger.com](https://sambeckbessinger.com/)
- Theme is Edition v.1.0.0
- I have a "Search" item in my Primary Navigation with the link: [https://www.sambeckbessinger.com/#searchinghost-easy](https://www.sambeckbessinger.com/#searchinghost-easy)

This is injected into my site footer:
```
<script src="https://cdn.jsdelivr.net/gh/gmfmi/searchinghost-easy@latest/dist/searchinghost-easy-backpack.js"></script>
<script>
//    $("ul.nav").append('<li class="nav-search"><a href="#searchinghost-easy"><svg style="fill:#fff" width="14px" height="14px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M508.875,493.792L353.089,338.005c32.358-35.927,52.245-83.296,52.245-135.339C405.333,90.917,314.417,0,202.667,0 S0,90.917,0,202.667s90.917,202.667,202.667,202.667c52.043,0,99.411-19.887,135.339-52.245l155.786,155.786 c2.083,2.083,4.813,3.125,7.542,3.125c2.729,0,5.458-1.042,7.542-3.125C513.042,504.708,513.042,497.958,508.875,493.792z M202.667,384c-99.979,0-181.333-81.344-181.333-181.333S102.688,21.333,202.667,21.333S384,102.677,384,202.667 S302.646,384,202.667,384z"/></svg></a></li>');
    
    new SearchinGhostEasy({
        contentApiKey: '7a1b175f0cedf079634fe6178c'
    });
</script>
```

If I uncomment the ul.nav line, I get this error in my js console when I load the site:
```
Uncaught ReferenceError: $ is not defined
    at www.sambeckbessinger.com/:864:5
```
No search icon appears in the nav bar, and clicking on the word "Search" in the menubar does nothing.

Any idea how I can fix this? Thanks!

**Comment by gmfmi** [comment]
Hey! Thanks for the kind words 😃

I had a quick look at your website and there is 2 issue to make it work:

1. To make that code works, the "jQuery" library is mandatory but your theme does not embed it.
2. That example (probably) only works on the Ghost default's theme. The HTML element "ul.nav" simply does not exist on yours.

I made a javascript-only version designed to work on your site. Here is the code to copy/paste:

```js
var searchIcon = '<svg style="fill:#fff" width="14px" height="14px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M508.875,493.792L353.089,338.005c32.358-35.927,52.245-83.296,52.245-135.339C405.333,90.917,314.417,0,202.667,0 S0,90.917,0,202.667s90.917,202.667,202.667,202.667c52.043,0,99.411-19.887,135.339-52.245l155.786,155.786 c2.083,2.083,4.813,3.125,7.542,3.125c2.729,0,5.458-1.042,7.542-3.125C513.042,504.708,513.042,497.958,508.875,493.792z M202.667,384c-99.979,0-181.333-81.344-181.333-181.333S102.688,21.333,202.667,21.333S384,102.677,384,202.667 S302.646,384,202.667,384z"/></svg>';
var menu = document.querySelector('nav.header-nav');
menu.insertAdjacentHTML('beforeend', `<a class="menu-item menu-item-contact" href="#searchinghost-easy">${searchIcon}</a>`);

new SearchinGhostEasy({
    contentApiKey: '7a1b175f0cedf079634fe6178c'
});
```

I hope it will work on first try! Please, let me know if you are still facing some issues (otherwise, feel free to close this issue).

Note: I also updated the README section to get rid of jQuery and hopefully support more themes by default ([b554bed](https://github.com/gmfmi/searchinghost-easy/commit/b554bed50b2ae09391b0080afad7b9be617c0b42))

**Comment by greenhamsam** [comment]
It works PERFECTLY. Really can't thank you enough!
